name: Build Android APK

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Buildozer
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential git zip unzip openjdk-17-jdk python3-pip autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo6 cmake libffi-dev libssl-dev
                      
          pip install --upgrade pip setuptools wheel buildozer cython


      - name: Set up Android SDK
        uses: android-actions/setup-android@v3   
      - name: Accept Android SDK licenses
        run: yes | sdkmanager --licenses
      - name: Build APK
        run:        
            yes | sdkmanager --licenses >/dev/null|
        mkdir -p ~/.buildozer/android/platform/android-sdk/licenses
        cp -r "$ANDROID_SDK_ROOT/licenses/." ~/.buildozer/android/platform/android-sdk/licenses/          buildozer android debug
        buildozer android debug
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: LiveGoldAI-APK
          path: bin/*.apk
